In [1]:
import pandas as pd
from scipy.stats import wilcoxon

In [2]:
headers = ["Model", "Dataset","Variate", "Lookback", "PredLength", "Seed", "MSE", "MAE"]

DLinear = pd.read_csv("Results_336/Result_DLinear.csv", sep="-", header=None, names=headers)
iTrans = pd.read_csv("Results_336/Result_iTransformer.csv", sep="-", header=None, names=headers)
Frnet = pd.read_csv("Results_336/Result_FrNet.csv", sep="-", header=None, names=headers)
PatchTST = pd.read_csv("Results_336/Result_PatchTST.csv", sep="-", header=None, names=headers)
ModelX = pd.read_csv("Results_336/Result_ModelX.csv", sep="-", header=None, names=headers)
#raw.head()

In [3]:
def setup(df):
    raw2 = df.copy()
    raw2["Seed"] = raw2["Seed"].apply(lambda x: x.replace("seed", ""))
    raw2["Lookback"] = raw2["Lookback"].apply(lambda x: x.replace("sl", ""))
    raw2["PredLength"] = raw2["PredLength"].apply(lambda x: x.replace("pl", ""))
    raw2["MSE"] = raw2["MSE"].apply(lambda x: x.replace("mse:", ""))
    raw2["MAE"] = raw2["MAE"].apply(lambda x: x.replace("mae:", ""))


    raw2["Seed"] = raw2["Seed"].astype(int)
    raw2["Lookback"] = raw2["Lookback"].astype(int)
    raw2["PredLength"] = raw2["PredLength"].astype(int)
    raw2["MSE"] = raw2["MSE"].astype(float)
    raw2["MAE"] = raw2["MAE"].astype(float)
    return raw2


dlinear_results = setup(DLinear)
itrans_results = setup(iTrans)
frnet_results = setup(Frnet)
patchtst_results = setup(PatchTST)
modelx_results = setup(ModelX)

In [4]:
# Mean and Standard Deviation for MSE and MAE for Lookback 336 for 5 different seeds

dlinear_tab = dlinear_results.groupby(["Dataset", "PredLength"]).agg({"MSE": ["mean", "std"], "MAE": ["mean", "std", "count"]})
itrans_tab = itrans_results.groupby(["Dataset", "PredLength"]).agg({"MSE": ["mean", "std"], "MAE": ["mean", "std", "count"]})
frnet_tab = frnet_results.groupby(["Dataset", "PredLength"]).agg({"MSE": ["mean", "std"], "MAE": ["mean", "std", "count"]})
patchtst_tab = patchtst_results.groupby(["Dataset", "PredLength"]).agg({"MSE": ["mean", "std"], "MAE": ["mean", "std", "count"]})
modelx_tab = modelx_results.groupby(["Dataset", "PredLength"]).agg({"MSE": ["mean", "std"], "MAE": ["mean", "std", "count"]})

In [5]:
modelx_tab

                         MSE                 MAE
                        mean       std      mean       std count
Dataset PredLength
ETTh1   48          0.375988  0.005861  0.418372  0.005364     5
        96          0.420615  0.007278  0.450396  0.003643     5
        192         0.480848  0.007411  0.489835  0.006239     5
        336         0.534734  0.008349  0.530014  0.003525     5
        512         0.574886  0.008529  0.552689  0.004185     5
        720         0.756607  0.022788  0.646772  0.008148     5
ETTh2   48          0.143736  0.002927  0.262325  0.002449     5
        96          0.180163  0.001507  0.291746  0.002334     5
        192         0.225192  0.011038  0.330865  0.009363     5
        336         0.245692  0.011387  0.351760  0.009881     5
        512         0.311346  0.015933  0.391090  0.012753     5
        720         0.388460  0.039660  0.447398  0.026600     5
ETTm1   48          0.323933  0.008169  0.364011  0.004261     5
        96          0.348445  0.005505  0.390762  0.006333     5
        192         0.393692  0.008516  0.422075  0.003425     5
        336         0.413266  0.001974  0.449225  0.002519     5
        512         0.453792  0.006678  0.475700  0.001974     5
        720         0.482805  0.012687  0.499085  0.006159     5
ETTm2   48          0.092268  0.001699  0.202955  0.001977     5
        96          0.108963  0.001832  0.223041  0.002809     5
        192         0.150090  0.004556  0.264156  0.002601     5
        336         0.185157  0.003545  0.298779  0.004174     5
        512         0.194438  0.002601  0.306618  0.002264     5
        720         0.245656  0.018489  0.342538  0.013944     5
WTH     48          0.111379       NaN  0.157046       NaN     1
        96          0.144468       NaN  0.195574       NaN     1
        192         0.179292       NaN  0.231743       NaN     1

In [6]:
frnet_tab

                         MSE                 MAE
                        mean       std      mean       std count
Dataset PredLength
ETTh1   48          0.373703  0.003762  0.411967  0.002216     5
        96          0.423994  0.003327  0.446684  0.002698     5
        192         0.493032  0.010683  0.491511  0.007907     5
        336         0.535810  0.011134  0.524475  0.009216     5
        512         0.560646  0.007076  0.537865  0.002309     5
        720         0.800883  0.015714  0.648640  0.008189     5
ETTh2   48          0.137848  0.004081  0.254438  0.003829     5
        96          0.171855  0.004042  0.284650  0.003005     5
        192         0.208416  0.010613  0.316496  0.007539     5
        336         0.226964  0.008696  0.339429  0.006556     5
        512         0.308399  0.007955  0.391824  0.006109     5
        720         0.331160  0.015906  0.401240  0.006135     5
ETTm1   48          0.315080  0.007027  0.357889  0.005921     5
        96          0.332604  0.004512  0.378300  0.005618     5
        192         0.391558  0.008751  0.417976  0.004093     5
        336         0.404823  0.008180  0.439587  0.001972     5
        512         0.456230  0.008325  0.472908  0.002256     5
        720         0.469229  0.008897  0.493303  0.007149     5
ETTm2   48          0.091998  0.000832  0.202797  0.001840     5
        96          0.108158  0.002253  0.220090  0.002296     5
        192         0.143367  0.004649  0.255951  0.004049     5
        336         0.184200  0.003263  0.293005  0.003157     5
        512         0.198919  0.010025  0.310350  0.009058     5
        720         0.245664  0.012503  0.343925  0.007194     5
WTH     48          0.111219  0.001445  0.152112  0.001098     5
        96          0.144985  0.000969  0.194006  0.001284     5
        192         0.183801  0.001614  0.233020  0.002221     5
        336         0.266040  0.001522  0.290531  0.000986     5
        512         0.311872  0.006334  0.320070  0.003345     5
        720         0.340482  0.009409  0.354472  0.003917     5

In [24]:
wilcoxon(pure336["MSE"].values, claw336["MSE"].values, alternative="greater")

WilcoxonResult(statistic=np.float64(1268.0), pvalue=np.float64(0.6018497588443786))